name: build-openlane-sky130
on: [push]

jobs:
  build-chacha-sky130:
    runs-on: ubuntu-latest
    env:
      REPO : chacha
      VLNV : secworks:crypto:chacha
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: chacha
      - name: Checkout pdk
        uses: actions/checkout@v2
        with:
          repository: olofk/pdklite
          path: pdklite
      - run: echo "PDK_ROOT=$GITHUB_WORKSPACE/pdklite" >> $GITHUB_ENV
      - run: echo "EDALIZE_LAUNCHER=${GITHUB_WORKSPACE}/openlane_runner.py" >> $GITHUB_ENV
      - run: pip3 install --user -e "git+https://github.com/olofk/edalize.git#egg=edalize"
      - run: pip3 install fusesoc
      - run: docker pull efabless/openlane:v0.12
      - run: wget https://raw.githubusercontent.com/olofk/subservient/main/openlane_runner.py
      - run: chmod +x openlane_runner.py
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=sky130 $VLNV

  sim-icarus:
    runs-on: ubuntu-latest
    env:
      REPO : chacha
      VLNV : secworks:crypto:chacha
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: chacha
      - run: sudo apt install iverilog
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=tb_chacha $VLNV
      - run: fusesoc run --target=tb_chacha_core $VLNV

  lint-verilator:
    runs-on: ubuntu-latest
    env:
      REPO : chacha
      VLNV : secworks:crypto:chacha
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: chacha
      - run: sudo apt install verilator
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=lint $VLNV